---
# file: ./homebrew/vars/main.yml

taps:
  - caskroom/cask
  - caskroom/versions
  - homebrew/boneyard

packages:
  - { name: ansible, state: present }
  - { name: awscli, state: present }
  - { name: fish, state: present }
  - { name: ghq, state: present }
  - { name: git, state: present }
  - { name: mas, state: present }
  - { name: peco, state: present }
  - { name: rmtrash, state: present }
  - { name: vim, state: present }
  - { name: tree, state: present }
